lesson2
comrade-sre/go_homework pull request #20
Opened 2021-12-15 15:11 UTC by comrade-sre

2021-12-19 15:23 UTC, v-lozhkin requested changes
Еще, лучше, разделять приложения на папки, иначе все в одной папке даже не запускается из-за редекларации методов

2021-12-19 15:23 UTC, v-lozhkin commented on tcp-chat/client.go
> +	//"golang.org/x/text/secure/precis"
Зачем комментить, но оставлять?

2021-12-19 15:23 UTC, v-lozhkin commented on tcp-chat/client.go
> +	defer conn.Close()
Об этом стоит позаботиться сразу после открытия коннекта

2021-12-19 15:23 UTC, v-lozhkin commented on tcp-chat/client.go
> +	conn, err := net.Dial("tcp", "localhost:8000")
Ошибки почти нигде не обрабатываются

2021-12-19 15:23 UTC, v-lozhkin commented on tcp-chat/server.go
> +		conn.Close()
Это лучше делать через defer

2021-12-19 15:23 UTC, v-lozhkin commented on tcp-chat/time_server.go
> +	listener, err := net.Listen(CONN_TYPE, fmt.Sprintf("s%:s%",CONN_HOST,CONN_PORT)
Этот код даже не компилируется, тут не хватает закрывающейся скобки

2021-12-19 15:23 UTC, v-lozhkin commented on tcp-chat/time_server.go
> +			message, _ := bufio.NewReader(os.Stdin).ReadString('\n')
Зачем каждый раз пересоздавать reader в цикле? Можно ведь это сделать выше, а тут просто делать ReadString

2021-12-19 15:23 UTC, v-lozhkin commented on tcp-chat/time_server.go
> +		close(messageChan)
Сюда вообще не понятно, когда рантайм дойдет, если выше идет бесконечный цикл без условия выхода

2021-12-19 15:23 UTC, v-lozhkin commented on tcp-chat/time_server.go
> +	listener, err := net.Listen(CONN_TYPE, fmt.Sprintf("s%:s%",CONN_HOST,CONN_PORT)
формат для sprintf тоже неверный (не s%, а %s)

2021-12-19 15:23 UTC, v-lozhkin commented on tcp-chat/time_server_graceful.go
> +	listener, err := net.Listen(CONN_TYPE, fmt.Sprintf("%s:%s", CONN_HOST, CONN_PORT))
Тоже ошибки не обрабатываются

2021-12-19 15:23 UTC, v-lozhkin commented on tcp-chat/time_server_graceful.go
> +	sigChan     = make(chan os.Signal)
Этот канал вообще не используется

2021-12-19 15:23 UTC, v-lozhkin commented on tcp-chat/time_server_graceful.go
> +		close(messageChan)
Те же проблемы, что в обычном сервере

2021-12-19 15:23 UTC, v-lozhkin commented on tcp-chat/time_server_graceful.go
> +func handleConn(wg sync.WaitGroup, ctx context.Context, c net.Conn, ch <-chan string) {
WaitGroup нужно передавать через поинтер

2021-12-19 15:23 UTC, v-lozhkin commented on tcp-chat/time_server_graceful.go
> +			wg.Done()
Тоже лучше через дефер

2021-12-19 15:23 UTC, v-lozhkin commented on tcp-chat/time_server_graceful.go
> +			conn, err := listener.Accept()
А еще оно не закрывается, потому что зависает тут на ожидании нового клиента, и не видит сообщение из канала

2021-12-21 15:46 UTC, comrade-sre commented on tcp-chat/client.go
> +	//"golang.org/x/text/secure/precis"
добавил обработку ошибок где не было, поправил синтаксический ошибки, неудачную реализацию graceful убрал, текущие работают нормально отвечая требованиям (Д|T)З

2021-12-25 12:43 UTC, v-lozhkin commented on tcp-chat/time_server.go
> +			message, _ := bufio.NewReader(os.Stdin).ReadString('\n')
Это все еще актуально

2021-12-25 12:44 UTC, v-lozhkin commented on tcp-chat/time_server.go
> +		close(messageChan)
Это тоже все еще актуально

2021-12-25 12:52 UTC, v-lozhkin approved these changes
Несколько недоработок остались, но в целом принято

2022-01-11 09:20 UTC, merged