dummy/file  srv
comrade-sre/go_homework pull request #21
Opened 2021-12-22 06:57 UTC by comrade-sre

2021-12-30 11:55 UTC, v-lozhkin commented on http/dummy_server.go
> +
?)

2021-12-30 11:57 UTC, v-lozhkin commented on http/dummy_server_test.go
> +		t.Errorf("handler returned unexpected body: got %v want %v",
Надо бы еще тест на, собственно, список файлов

2021-12-30 11:59 UTC, v-lozhkin requested changes
Крайне странно перемешаны обработчики. 
Надо чтобы был сервис, которые имеет три эндпоинта - для загрузки  файлов, для их скачивания, и для получения списка. А то сейчас получается плохочитаемая каша

2021-12-30 12:46 UTC, comrade-sre commented
вообще, тут все по заданию и опираясь на код из методички. там две сервера а не один, только для файлового сделан дополнительный функционал...

2022-01-04 18:20 UTC, v-lozhkin commented
> вообще, тут все по заданию и опираясь на код из методички. там две сервера а не один, только для файлового сделан дополнительный функционал...

Хорошо, действительно, в методичке так. 
Но не мешает добавить тестов на остальные эндпоинты

2022-01-11 09:19 UTC, merged