Lesson5
comrade-sre/go_homework pull request #5
Opened 2020-12-23 15:58 UTC by comrade-sre

Выполнил задание из книги Кернигана, там есть хороший пример обработки ошибок пори открытии файла
В других моих скриптах так же присутствует валидация данных, и обработка возвращаемых значений, например в вычислении числа Фибоначчи

2020-12-29 21:45 UTC, rumyantseva requested changes
С функцией printLines мне прям как-то тяжело :) 
Предлагаю улучшить часть про обработку ошибок в сканере (см. комменты)

2020-12-29 21:45 UTC, rumyantseva commented on dup.go
> +			f.Close()
Вот здесь очень правильный момент, что f.Close именно явно вызывается, а не деферится! Это правильно! Таким образом, мы в каждой итерации освобождаем память, выделенную под дескриптор файла. Но в самом f.Close тоже может быть ошибка, ее обычно особо не обрабатывают, но может быть полезно выводить ее в логи для лучшей видимости всего происзодящего.

2020-12-29 21:45 UTC, rumyantseva commented on dup.go
> +			isFile = false
Про isFile на первый взгляд логику понять не могу, вот такие штуки может быть полезно документировать.

2020-12-29 21:45 UTC, rumyantseva commented on dup.go
> +func printLines(counts map[string]int, isFile bool) bool {
По сигнатуре немного странно, что функция как бы что-то печатает, но еще и возвращает bool. Не самое очевидное решение в плане того, что в этом bool содержится, когда он true и когда false.

2020-12-29 21:45 UTC, rumyantseva commented on dup.go
> +	for input.Scan() {
Вот здесь в реальной жизни надо поаккуратнее. input.Scan может вернуть false не только, когда достигнут конец файла, но и когда произошла ошибка. Поэтому, как только input.Scan вернул false неплохо было бы вызвать input.Err(), чтобы убедиться, что ошибки всё же не было. Собственно, [в доках к методу Scan](https://golang.org/pkg/bufio/#Scanner.Scan) это упоминается.

2020-12-30 08:31 UTC, comrade-sre commented on dup.go
> +			isFile = false
флаг при передаче отвечает за то, является ли содежимым файла перданный инпут, при возврате сбрасывается в случае если найдены дупликаты. При обработке обычного стандартонго ввода, никака не влияет на поведение

2020-12-30 08:31 UTC, comrade-sre commented on dup.go
> +	for input.Scan() {
добавил обработку ошибок после цикла

2020-12-30 08:33 UTC, merged